version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - localstack
      - mongodb
    networks:
      - climate3
    hostname: backend

  sync-webhook:
    build:
      context: ./sync-webhook
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - sync-webhook/.env
    depends_on:
      - localstack
      - mongodb
      - backend
    networks:
      - climate3
    hostname: sync-webhook

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5173:5173
  #   depends_on:
  #     - backend
  #   environment:
  #    - REACT_APP_API_URL=http://backend:5000/api
  #   networks:
  #     - climate3
  #   hostname: frontend

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,lambda
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=30
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_DOCKER_NETWORK=climate3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack_data:${PWD}/data/localstack
    networks:
      - climate3
    hostname: localstack

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=changeme
      - MONGO_INITDB_DATABASE=testdb
    volumes:
      - mongo_data:${PWD}/data/mongodb
    networks:
      - climate3
    hostname: mongodb

volumes:
  localstack_data:
  mongo_data:

networks:
  climate3:
    driver: bridge
